#pragma once

#define DEFAULT_KEY_UP    65
#define DEFAULT_KEY_DOWN  66
#define DEFAULT_KEY_LEFT  68
#define DEFAULT_KEY_RIGHT 67
#define DEFAULT_KEY_ENTER 10
#define DEFAULT_KEY_ESCAPE 27
#define DEFAULT_KEY_SPECIAL_PREFIX 91
#define DEFAULT_KEY_SCROLL_UP 65
#define DEFAULT_KEY_SCROLL_DOWN 66
#define DEFAULT_KEY_BACKSPACE 127

#define SUCCESS_STEEPNESS 0.1
#define STARTER_GOLD 100
#define SUCCESS_ADV_TEAM_DIVISOR 4
#define FAILURE_ADV_DIVISOR 3
#define MATCHING_TAG_POINTS 5
#define NONMATCHING_TAG_POINTS 1
#define GOLD_ELIMINATION_MISSION_LEVEL_MUPLTIPLIER 5
#define GOLD_TRAINING_MISSION_LEVEL_MUPLTIPLIER 3
#define LOST_ADVENTURER_COST 10