#pragma once

#define DEFAULT_KEY_UP    65
#define DEFAULT_KEY_DOWN  66
#define DEFAULT_KEY_LEFT  68
#define DEFAULT_KEY_RIGHT 67
#define DEFAULT_KEY_ENTER 10
#define DEFAULT_KEY_ESCAPE 27
#define DEFAULT_KEY_SPECIAL_PREFIX 91
#define DEFAULT_KEY_SCROLL_UP 65
#define DEFAULT_KEY_SCROLL_DOWN 66
#define DEFAULT_KEY_BACKSPACE 127
#define DEFAULT_KEY_SPACE 32

#define SUCCESS_STEEPNESS 0.1
#define STARTER_GOLD 200
#define STARTER_LEVEL 1
#define SUCCESS_ADV_TEAM_DIVISOR 4
#define FAILURE_ADV_DIVISOR 3
#define MATCHING_TAG_POINTS 5
#define NONMATCHING_TAG_POINTS 1
#define GOLD_ELIMINATION_MISSION_LEVEL_MUPLTIPLIER 5
#define GOLD_TRAINING_MISSION_LEVEL_MUPLTIPLIER 3
#define LOST_ADVENTURER_COST 10
#define NEGATIVE_MOD_CHANCE_FAILURE 20
#define NEGATIVE_MOD_CHANCE_SUCCESS 10
#define POSITIVE_MOD_CHANCE 30
#define NO_FOOD_SUBSTRACT 40
#define DAYS_COMPLETE_TRAINING_MISSION 1
#define GOLD_PER_LEVEL 3
#define DAILY_MISSIONS_COUNT 3
#define DAILY_ADVENTURER_COUNT 4
#define MAX_ADVENTURERS_PER_MISSION 4
#define MAX_ADDITIONAL_STAT_INCREASE 5
#define RANDOM_ADD_SALARY 15
#define BASE_SALARY 15
#define MISSION_MAX_ADD_LEVEL 10

#define CARDS_PADDING 3
#define MAX_OPTIONS_ADV_SELECTION 5

#define STATS_COUNT 7

// #define WINDOW_RENDER_DEBUG