#pragma once

#define DEFAULT_KEY_UP    65
#define DEFAULT_KEY_DOWN  66
#define DEFAULT_KEY_LEFT  68
#define DEFAULT_KEY_RIGHT 67
#define DEFAULT_KEY_ENTER 10
#define DEFAULT_KEY_ESCAPE 27
#define STARTER_GOLD 100